---

- hosts: 192.168.1.62 
  vars:
   - ip_address: '192.168.1.62'
  become: true

  tasks:
  - name: disable ufw
    command: systemctl disable ufw

  - name: stop ufw
    command: systemctl stop ufw

  - name: Copy sshd file
    copy:
      src: /home/halam/git_stuff/ubuntu/sshd_config
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: '0644'
    notify:
     - restart ssh

  - name: Copy netplan
    template:
      src: /home/halam/git_stuff/ubuntu/01-netcfg.yaml
      dest: /etc/netplan/01-netcfg.yaml
    notify:
     - netplan apply

  handlers:
   - name: restart ssh
     service:
       name: sshd
       state: restarted
  
   - name: netplan apply
     command: netplan apply
